openapi: 3.0.0
info:
  title: H+ sports Catalog
  description: Sports catalog items
  termsOfService: terms
  contact:
    name: krupa
    email: shreekrupa@gmail.com
  version: 1.0.0
servers:
- url: /
paths:
  /product:
    get:
      parameters:
      - name: pageNumber
        in: query
        description: Page number to return
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 1
      - name: pageSize
        in: query
        description: Number of results in a page
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 10
      responses:
        "200":
          description: please find the list of products in catalog
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200'
    post:
      description: adding a product to the catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
      responses:
        "201":
          description: product added
  /product/{productId}:
    get:
      parameters:
      - name: productId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 4567
      responses:
        "200":
          description: this is the product you are looking for
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
components:
  schemas:
    product:
      required:
      - name
      type: object
      properties:
        id:
          type: integer
          example: 1234
        name:
          type: string
          example: yoga pant
        description:
          type: string
          example: yoga pant
        image-title:
          type: string
          example: comfort yoga pant
    inline_response_200:
      properties:
        id:
          type: integer
          example: 100
        name:
          type: string
          example: shorts
